# Development Docker Compose Override
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  api:
    build:
      context: .
      target: base
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/app/__pycache__
    environment:
      - DEBUG=true
      - RELOAD=true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug

  worker:
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/app/__pycache__
    environment:
      - DEBUG=true
    command: celery -A app.services.video_service.celery_app worker --loglevel=debug --concurrency=1 -E

  # Add development database browser
  mongo-express:
    image: mongo-express:latest
    container_name: video-api-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongodb
    networks:
      - video-api-network
